name: Node.js CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Adjust Node.js version as per your project requirements

    - name: Install dependencies
      run: |
        cd apps/React-GithubActions
        npm install --only=prod

    - name: Build React app
      run: |
        cd apps/React-GithubActions
        npm run build

    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          sudo mv ~/apps/React-GithubActions/dist /var/www/ReactActions/

