name: Node.js CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust to a valid Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/apps/React-GithubActions/
          git pull
          git status
          npm run build
          # Move dist directory to /var/www/ReactActions
          mkdir -p /var/www/ReactActions
          mv dist /var/www/ReactActions
          # Ensure npm is in the PATH
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          # Check if npm is available
          which npm || { echo "npm is not installed"; exit 1; }
          
          # Optionally, restart server using pm2
          # pm2 restart server
